modify the poster picking so we don't run on the same poster twice du…
WildCodeSchool/2022-03-JS-Reims-project-2-posteries pull request #31
Opened 2022-05-05 09:50 UTC by Valentin-Morette

…ring the game

2022-05-10 07:21 UTC, nibor51 requested changes

2022-05-10 07:21 UTC, nibor51 commented on frontend/src/context/ApiCallsContext.jsx
> +    movieIdArray.push(movieIdArray.splice(0, 1));
With this we lose the notion of randomness during the game. You have to move four cards and not one! Try with a state and by making a shift of 4 "notches" in your table for each question.

2022-05-10 08:53 UTC, nibor51 requested changes
I don't see the state, nor the shift

2022-05-10 12:25 UTC, nibor51 commented on frontend/src/pages/Play.jsx
> +    pickMovie(movieIdArray, (count + 1) * 4);
move the multiplication into the function

2022-05-10 12:25 UTC, nibor51 commented on frontend/src/pages/Play.jsx
> +    pickMovie(movieIdArray, count * 4);
same one

2022-05-10 12:31 UTC, nibor51 requested changes
currently in your function you never use the first 4 films.
To fix this, set count to zero and don't multiply it.

Hint : In the JSX, there you can add one to count to see it

2022-05-11 06:58 UTC, rocambille requested changes

2022-05-11 06:58 UTC, rocambille commented on frontend/src/pages/Play.jsx
> +    pickMovie(movieIdArray, count + 1);
count is starting at 1 and you're adding one here: you're droping the eight first elements

2022-05-11 08:00 UTC, merged